
name: Deploy

on:
  push:
    branches:
      #- main
      - nix
jobs:
  build:
    name: "Deploy project on live-dev server"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: github
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST}}

      - name: Check SSH Connection
        run: ssh staging 'echo "It works!"'

      - name: Pull project code from main branch CICDTesting with hard reset
        run: ssh staging 'cd CICDTesting && git reset --hard && git pull origin main'

      - name: Set build time for web display
        run: ssh staging 'npm --prefix ./CICDTesting run update_build_date'

      - name: Deploy next-project
        run: ssh staging 'npm --prefix ./CICDTesting i & npm --prefix ./CICDTesting run deploy'
        
      - name: Create PHP API folder 
        run: ssh staging 'mkdir ./CICDTesting/out/api'
        
      - name: Copy PHP files
        run: ssh staging 'cp -a ./CICDTesting/api ./CICDTesting/out'
        
      - name: Copy all deployed files to www directory
        run: ssh staging 'sudo cp -a ./CICDTesting/out/ /var/www'
        
      - name: Delete previous deploy files
        run: ssh staging 'sudo rm -r -d /var/www/CICDTesting'
        
      - name: Rename www directory
        run: ssh staging 'sudo mv /var/www/out/ /var/www/CICDTesting'