name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: List Contents of Directory
        run: cd CICDTesting && ls
      
      - name: Install dependencies
        run: ls && npm i

      - name: Build Angular App
        run: npm run build
